- id: circleci_validate
  name: Validate CircleCI config
  description: This hook validates CircleCI config
  entry: circleci-validate
  language: python
  files: .circleci/.*.yml
  pass_filenames: false
- id: circleci_process
  name: Process CircleCI configuration
  description: This hook process CircleCI configuration
  entry: circleci-process
  language: python
  files: .circleci/.*.yml
  pass_filenames: false
